import serial
import argparse 
from time import sleep 

def main(args):
    ser = serial.Serial()
    if args.baud:
        ser.baudrate = int(args.baud)
    else:
        ser.baudrate = 38400
    ser.port = args.port
    ser.open()
    ser.flushInput()
    ser.flushOutput()
    f = open(args.file, "r")
    
    data = bytearray()
    
    while True:
        ch=f.read(1)
        if not ch: 
            data.extend(chr(4))
            break
        data.extend(ch)
     
    data = bytearray([8, ord('b'), 1,\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        0, 2,\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('d'),ord('c'),\
                        ord('a'), ord('b'), ord('c'),ord('c'),ord('c'),ord('c'),\
                        0, 4])
    print data 
    ser.write(data)
    sleep(.1)
    
    print "Done Transmitting"
    rec = bytearray()
    i = 0
    while i < 8:
        ch = ser.read()
        rec.extend(ch)
        i += 1
            
    ser.flush()      
    ret_val = rec[0] | (rec[1] << 8) | (rec[2] << 16) | (rec[3] << 24) 
    clk_cnt = rec[4] | (rec[5] << 8) | (rec[6] << 16) | (rec[7] << 24) 
	
    str = "Return Val: %d 0x%08x" % (ret_val , ret_val)
    print str 
    str = "Clk Count: %d " % clk_cnt
    print str
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Send data to the spart")
    parser.add_argument('-p', '--port', required=True, help="Serial Port")
    parser.add_argument('-b', '--baud', required=False, help="Baud Rate - Default 38400")
    parser.add_argument('-f', '--file', required=True, help="File to Send")
    main(parser.parse_args())
