
	'''new_scope : '''	
	'''finish_scope : '''
	'''identifier : IDENTIFIER'''
	'''constant : INTEGER'''
	'''constant : LONGINTEGER'''
	'''constant : HEXADECIMAL'''
        '''constant : LONGHEXADECIMAL'''
        '''constant : DECIMALFLOAT'''
        '''constant : DECIMALDOUBLE'''
        '''constant : FLOATVAL'''
        '''constant : DOUBLEVAL'''
        '''constant : CHARACTER'''
        '''constant : ESCAPECHAR'''
        '''constant : HEXLITERAL'''
        '''constant : STRING'''        
        '''primary_expression : identifier'''        
      '''primary_expression : constant'''
      '''primary_expression : '(' expression ')'       '''
      '''postfix_expression : primary_expression'''
      '''postfix_expression : postfix_expression '[' expression ']'       '''
      '''postfix_expression : postfix_expression '(' ')'      '''
      '''postfix_expression : postfix_expression '(' argument_expression_list ')'      '''
      '''postfix_expression : postfix_expression '.' identifier'''
      '''postfix_expression : postfix_expression PTR_OP identifier'''
      '''postfix_expression : postfix_expression INC_OP'''
      '''postfix_expression : postfix_expression DEC_OP'''
      '''argument_expression_list : assignment_expression'''
      '''argument_expression_list : argument_expression_list ',' assignment_expression'''
      '''unary_expression : postfix_expression'''
      '''unary_expression : INC_OP unary_expression'''
      '''unary_expression : DEC_OP unary_expression'''
      '''unary_expression : unary_operator cast_expression'''
      '''unary_expression : SIZEOF unary_expression'''
      '''unary_expression : SIZEOF '(' type_name ')'      '''
      '''unary_operator : '&'      '''
      '''unary_operator : '*'      '''
      '''unary_operator : '+'      '''
      '''unary_operator : '-'      '''
      '''unary_operator : '~'      '''
      '''unary_operator : '!'      '''
      '''cast_expression : unary_expression'''
      '''cast_expression : '(' type_name ')' cast_expression'''
      '''multiplicative_expression : cast_expression'''
      '''multiplicative_expression : multiplicative_expression '*' cast_expression'''
      '''multiplicative_expression : multiplicative_expression '/' cast_expression'''
      '''multiplicative_expression : multiplicative_expression '%' cast_expression'''
      '''additive_expression : multiplicative_expression'''
      '''additive_expression : additive_expression '+' multiplicative_expression'''
      '''additive_expression : additive_expression '-' multiplicative_expression'''
      '''shift_expression : additive_expression'''
      '''shift_expression : shift_expression LEFT_OP additive_expression'''
      '''shift_expression : shift_expression RIGHT_OP additive_expression'''
      '''relational_expression : shift_expression'''
      '''relational_expression : relational_expression '<' shift_expression'''
      '''relational_expression : relational_expression '>' shift_expression'''
      '''relational_expression : relational_expression LE_OP shift_expression'''
      '''relational_expression : relational_expression GE_OP shift_expression'''
      '''equality_expression : relational_expression'''
      '''equality_expression : equality_expression EQ_OP relational_expression'''
      '''equality_expression : equality_expression NE_OP relational_expression'''
      '''and_expression : equality_expression'''
      '''and_expression : and_expression '&' equality_expression'''
      '''exclusive_or_expression : and_expression'''
      '''exclusive_or_expression : exclusive_or_expression '^' and_expression'''
      '''inclusive_or_expression : exclusive_or_expression'''
      '''inclusive_or_expression : inclusive_or_expression '|' exclusive_or_expression'''
      '''logical_and_expression : inclusive_or_expression'''
      '''logical_and_expression : logical_and_expression AND_OP inclusive_or_expression'''
      '''logical_or_expression : logical_and_expression'''
      '''logical_or_expression : logical_or_expression OR_OP logical_and_expression'''
      '''conditional_expression : logical_or_expression'''
      '''conditional_expression : logical_or_expression '?' expression ':' conditional_expression'''
      '''assignment_expression : conditional_expression'''
      '''assignment_expression : unary_expression assignment_operator assignment_expression'''
      '''equal_to : '='      '''
      '''assignment_operator : equal_to'''
      '''assignment_operator : MUL_ASSIGN'''      
      '''assignment_operator : DIV_ASSIGN'''
      '''assignment_operator : MOD_ASSIGN'''
      '''assignment_operator : ADD_ASSIGN'''
      '''assignment_operator : SUB_ASSIGN'''
      '''assignment_operator : LEFT_ASSIGN'''
      '''assignment_operator : RIGHT_ASSIGN'''
      '''assignment_operator : AND_ASSIGN'''
      '''assignment_operator : XOR_ASSIGN'''
      '''assignment_operator : OR_ASSIGN'''
      '''expression : assignment_expression'''
      '''expression : expression ',' assignment_expression'''
      '''constant_expression : conditional_expression'''
      '''declaration : declaration_specifiers ';'      '''
      '''declaration : declaration_specifiers error'''
      '''declaration : declaration_specifiers init_declarator_list ';'      '''
      '''declaration : declaration_specifiers init_declarator_list error'''
      '''declaration_specifiers : type_qualifier'''
      '''declaration_specifiers : type_specifier'''
      '''declaration_specifiers : storage_class_specifier'''
      '''declaration_specifiers : type_qualifier type_specifier'''
      '''declaration_specifiers : type_specifier type_qualifier'''
      '''declaration_specifiers : type_specifier storage_class_specifier'''
      '''declaration_specifiers : storage_class_specifier type_specifier'''
      '''declaration_specifiers : storage_class_specifier type_qualifier'''
      '''declaration_specifiers : type_qualifier storage_class_specifier'''
      '''declaration_specifiers : type_qualifier type_specifier storage_class_specifier'''
      '''declaration_specifiers : type_qualifier storage_class_specifier type_specifier'''
      '''declaration_specifiers : storage_class_specifier type_specifier type_qualifier'''
      '''declaration_specifiers : storage_class_specifier type_qualifier type_specifier'''
      '''declaration_specifiers : type_specifier type_qualifier storage_class_specifier'''
      '''declaration_specifiers : type_specifier storage_class_specifier type_qualifier'''
      '''init_declarator_list : init_declarator'''
      '''init_declarator_list : init_declarator_list ',' init_declarator'''
      '''init_declarator : declarator equal_to initializer'''
      '''init_declarator : declarator'''
      '''storage_class_specifier : TYPEDEF'''
      '''storage_class_specifier : EXTERN'''
      '''storage_class_specifier : STATIC'''
      '''storage_class_specifier : AUTO'''
      '''storage_class_specifier : REGISTER'''
      '''type_specifier : VOID'''
      '''type_specifier : CHAR'''
      '''type_specifier : SHORT'''
      '''type_specifier : INT'''
      '''type_specifier : LONG'''
      '''type_specifier : FLOAT'''
      '''type_specifier : DOUBLE'''
      '''type_specifier : SIGNED'''
      '''type_specifier : UNSIGNED'''
      '''type_specifier : struct_or_union_specifier'''
      '''type_specifier : enum_specifier'''
      '''type_specifier : TYPE_NAME'''
      '''struct_or_union_specifier : struct_or_union identifier '{' struct_declaration_list '}'      '''
      '''struct_or_union_specifier : struct_or_union '{' struct_declaration_list '}'      '''
      '''struct_or_union_specifier : struct_or_union identifier'''
      '''struct_or_union : STRUCT'''
      '''struct_or_union : UNION'''
      '''struct_declaration_list : struct_declaration'''
      '''struct_declaration_list : struct_declaration_list struct_declaration'''
      '''struct_declaration : specifier_qualifier_list struct_declarator_list ';'      '''
      '''specifier_qualifier_list : type_specifier specifier_qualifier_list'''
      '''specifier_qualifier_list : type_specifier'''
      '''specifier_qualifier_list : type_qualifier specifier_qualifier_list'''
      '''specifier_qualifier_list : type_qualifier'''
      '''struct_declarator_list : struct_declarator'''
      '''struct_declarator_list : struct_declarator_list ',' struct_declarator'''
      '''struct_declarator : declarator'''
      '''struct_declarator : ':' constant_expression'''
      '''struct_declarator : declarator ':' constant_expression'''
      '''enum_specifier : ENUM '{' enumerator_list '}'      '''
      '''enum_specifier : ENUM identifier '{' enumerator_list '}'      '''
      '''enum_specifier : ENUM identifier'''
      '''enumerator_list : enumerator'''
      '''enumerator_list : enumerator_list ',' enumerator'''
      '''enumerator : identifier'''
      '''enumerator : identifier '=' constant_expression'''
      '''type_qualifier : CONST'''
      '''type_qualifier : VOLATILE'''
      '''declarator : pointer declarator'''
      '''declarator : direct_declarator'''
      '''set_parameter_flag : '''
      '''unset_parameter_flag : '''
      '''direct_declarator : identifier'''
      '''direct_declarator : '(' declarator ')'      '''
      '''direct_declarator : direct_declarator '[' constant_expression ']'      '''
      '''direct_declarator : direct_declarator '[' ']'      '''
      '''direct_declarator : direct_declarator '(' set_parameter_flag parameter_type_list unset_parameter_flag ')'      '''
      '''direct_declarator : direct_declarator '(' set_parameter_flag identifier_list unset_parameter_flag ')'      '''
      '''direct_declarator : direct_declarator '(' ')'      '''
      '''pointer : '*'      '''
      '''pointer : '*' type_qualifier_list'''
      '''pointer : '*' pointer'''
      '''pointer : '*' type_qualifier_list pointer'''
      '''type_qualifier_list : type_qualifier'''
      '''type_qualifier_list : type_qualifier_list type_qualifier'''
      '''parameter_type_list : parameter_list'''
      '''parameter_type_list : parameter_list ',' ELLIPSIS'''
      '''parameter_list : parameter_declaration'''
      '''parameter_list : parameter_list ',' parameter_declaration'''
      '''parameter_declaration : declaration_specifiers declarator'''
      '''parameter_declaration : declaration_specifiers abstract_declarator'''
      '''parameter_declaration : declaration_specifiers'''
      '''identifier_list : identifier'''
      '''identifier_list : identifier_list ',' identifier'''
      '''type_name : specifier_qualifier_list'''
      '''type_name : specifier_qualifier_list abstract_declarator'''
      '''abstract_declarator : pointer'''
      '''abstract_declarator : direct_abstract_declarator'''
      '''abstract_declarator : pointer direct_abstract_declarator'''
      '''direct_abstract_declarator : '(' abstract_declarator ')'      '''
      '''direct_abstract_declarator : '[' ']'      '''
      '''direct_abstract_declarator : '[' constant_expression ']'      '''
      '''direct_abstract_declarator : direct_abstract_declarator '[' ']'      '''
      '''direct_abstract_declarator : direct_abstract_declarator '[' constant_expression ']'      '''
      '''direct_abstract_declarator : '(' ')'      '''
      '''direct_abstract_declarator : '(' parameter_type_list ')'      '''
      '''direct_abstract_declarator : direct_abstract_declarator '(' ')'      '''
      '''direct_abstract_declarator : direct_abstract_declarator '(' parameter_type_list ')'      '''
      '''initializer : assignment_expression'''
      '''initializer : '{' initializer_list '}'      '''
      '''initializer : '{' initializer_list ',' '}'      '''
      '''initializer_list : initializer'''
      '''initializer_list : initializer_list ',' initializer'''
      '''statement : labeled_statement'''
      '''statement : compound_statement'''
      '''statement : expression_statement'''
      '''statement : selection_statement'''
      '''statement : iteration_statement'''
      '''statement : jump_statement'''
      '''labeled_statement : identifier ':' statement'''
      '''labeled_statement : CASE constant_expression ':' statement'''
      '''labeled_statement : DEFAULT ':' statement'''
      '''compound_statement : '{' '}'      '''
      '''compound_statement : '{' new_scope compound_statement_list finish_scope '}'      '''
      '''compound_statement : '{' new_scope compound_declaration_list finish_scope '}'      '''
      '''compound_statement_list : declaration_list'''
      '''compound_statement_list : declaration_list compound_declaration_list'''
      '''compound_declaration_list : statement_list'''
      '''compound_declaration_list : statement_list compound_statement_list'''
      '''declaration_list : declaration'''
      '''declaration_list : declaration_list declaration'''
      '''statement_list : statement'''
      '''statement_list : statement_list statement'''
      '''expression_statement : ';'      '''
      '''expression_statement : expression ';'      '''
      '''expression_statement : expression error'''
      '''get_labels : '''
      '''release_labels : '''
      '''switch_label : '''
      '''release_switch_label : '''
      '''selection_statement : IF '(' expression ')' statement %prec IFX'''
      '''selection_statement : IF '(' expression ')' statement ELSE statement'''
      '''selection_statement : SWITCH get_labels '(' expression ')' switch_label statement release_switch_label release_labels'''
      '''iteration_statement : WHILE get_labels '(' expression ')' statement release_labels'''
      '''iteration_statement : DO get_labels statement WHILE '(' expression ')' ';' release_labels'''
      '''iteration_statement : FOR get_labels '(' expression_statement expression_statement _embed0_iteration_statement ')' statement release_labels'''
      '''iteration_statement : FOR get_labels '(' expression_statement expression_statement expression _embed1_iteration_statement ')' statement release_labels'''
      '''_embed0_iteration_statement : '''
      '''_embed1_iteration_statement : '''
      '''jump_statement : GOTO identifier ';'    '''
      '''jump_statement : CONTINUE ';'      '''
      '''jump_statement : BREAK ';'      '''
      '''jump_statement : RETURN ';'      '''
      '''jump_statement : RETURN expression ';'      '''
      '''strt : strt1 | CLASS IDENTIFIER '{' strt1 '}' | strt strt1 '''
      '''strt1 : external_declaration'''
      '''strt1 : strt1 external_declaration'''
      '''external_declaration : function_definition'''
      '''external_declaration : declaration'''
      '''function_scope : '''      
      '''unset_function_scope : '''
      '''function_definition : declaration_specifiers declarator declaration_list function_scope get_labels compound_statement release_labels unset_function_scope'''
      '''function_definition : declaration_specifiers declarator function_scope get_labels compound_statement release_labels unset_function_scope'''
      '''function_definition : declarator declaration_list function_scope get_labels compound_statement release_labels unset_function_scope'''
      '''function_definition : declarator function_scope get_labels compound_statement release_labels unset_function_scope'''
